import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Nexus Pro Headphones',
    description: 'High-fidelity audio with active noise cancellation and 40-hour battery life.',
    price: 299.99,
    discountPrice: 249.99,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/headphones/800/600',
    rating: 4.8,
    reviews: 128,
    stock: 15,
  },
  {
    id: '2',
    name: 'Aura Smart Watch',
    description: 'Track your health, fitness, and notifications with this sleek, waterproof smartwatch.',
    price: 199.99,
    discountPrice: 159.99,
    category: 'Wearables',
    image: 'https://picsum.photos/seed/watch/800/600',
    rating: 4.5,
    reviews: 85,
    stock: 22,
  },
  {
    id: '3',
    name: 'Lumina Desk Lamp',
    description: 'Adjustable brightness and color temperature with a built-in wireless charger.',
    price: 79.99,
    category: 'Home Office',
    image: 'https://picsum.photos/seed/lamp/800/600',
    rating: 4.7,
    reviews: 56,
    stock: 40,
  },
  {
    id: '4',
    name: 'Zenith Mechanical Keyboard',
    description: 'Tactile mechanical switches with customizable RGB lighting and ergonomic design.',
    price: 149.99,
    category: 'Computing',
    image: 'https://picsum.photos/seed/keyboard/800/600',
    rating: 4.9,
    reviews: 210,
    stock: 12,
  },
  {
    id: '5',
    name: 'Vortex Gaming Mouse',
    description: 'Ultra-lightweight gaming mouse with 20K DPI sensor and programmable buttons.',
    price: 69.99,
    category: 'Computing',
    image: 'https://picsum.photos/seed/mouse/800/600',
    rating: 4.6,
    reviews: 145,
    stock: 30,
  },
  {
    id: '6',
    name: 'Prism 4K Monitor',
    description: '27-inch 4K UHD display with HDR support and ultra-thin bezels.',
    price: 449.99,
    category: 'Computing',
    image: 'https://picsum.photos/seed/monitor/800/600',
    rating: 4.8,
    reviews: 92,
    stock: 8,
  },
];
